# Generated by Django 4.1.1 on 2022-10-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetAPI", "0002_alter_expense_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(default=""),
        ),
    ]
