# Generated by Django 4.1.1 on 2022-10-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetAPI", "0004_remove_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
